[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://vutsmvnevjhmsxfhmfle.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1dHNtdm5ldmpobXN4ZmhtZmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDk4ODAsImV4cCI6MjA2MDU4NTg4MH0.UvDSkCkk9LKycGgi5HI55-RZyMScheXC9aVz4X8o9-g"
  VITE_TAVUS_API_KEY = ".."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/functions/v1/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"